@Api_HostAddress = http://localhost:5158

// Set the tracking ID of a job here to cancel / check progress
@JobId = 1d0eec40-3cb4-4118-97e9-09f1136b1b84

### Job queue (start)

POST {{Api_HostAddress}}/job-queue
Accept: application/json
Content-Type: application/json

{
    "FirstName": "John",
    "LastName": "Smith"
}

### Job queue (result)

GET {{Api_HostAddress}}/job-queue/result/{{JobId}}
Accept: application/json

### Job queue (cancel)

POST {{Api_HostAddress}}/job-queue/cancel/{{JobId}}
Accept: application/json
