@Example_FastEndpoints.Api_HostAddress = http://localhost:5158
@UserId = 1

### GetUser

GET {{Example_FastEndpoints.Api_HostAddress}}/users/{{UserId}}
Accept: application/json

### Pre / Post Processor

GET {{Example_FastEndpoints.Api_HostAddress}}/processors
Accept: application/json

### Event bus

GET {{Example_FastEndpoints.Api_HostAddress}}/events
Accept: application/json

### Command bus

GET {{Example_FastEndpoints.Api_HostAddress}}/commands
Accept: application/json

### Job queue (start)

POST {{Example_FastEndpoints.Api_HostAddress}}/job-queue
Accept: application/json
Content-Type: application/json

{
    "FirstName": "John",
    "LastName": "Smith"
}

### <<Set return value of previous call here>>

@JobId = 1d0eec40-3cb4-4118-97e9-09f1136b1b84

### Job queue (result)

GET {{Example_FastEndpoints.Api_HostAddress}}/job-queue/result/{{JobId}}
Accept: application/json

### Job queue (cancel)

POST {{Example_FastEndpoints.Api_HostAddress}}/job-queue/cancel/{{JobId}}
Accept: application/json

### RPC - Remote command bus

GET {{Example_FastEndpoints.Api_HostAddress}}/rpc/command?firstNumber=2&secondNumber=3
Accept: application/json

### Failure (Validation Error)

GET {{Example_FastEndpoints.Api_HostAddress}}/users/0
Accept: application/json

### Failure (Not Found)

GET {{Example_FastEndpoints.Api_HostAddress}}/users/255
Accept: application/json

### Problem details via SendErrorsAsync()

GET {{Example_FastEndpoints.Api_HostAddress}}/problem-details/send-error
Accept: application/json

### Using FastEndpoint's ProblemDetails

GET {{Example_FastEndpoints.Api_HostAddress}}/problem-details/explicit
Accept: application/json

### Using an extension method to wrap creating an MVC problem details

GET {{Example_FastEndpoints.Api_HostAddress}}/problem-details/mvc
Accept: application/json
